pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: docker build buildah -t buildah
    displayName: 'Build Buildah image'

  - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
    inputs:
      keyfile: 'derex/builder/openedx-alpine/.cache_id'
      targetfolder: 'cache/'
      vstsFeed: '8b1737d6-762a-438d-acf4-e55593dc7819'

  - script: |
      set -x
      mkdir -p cache/pip-alpine cache/apk cache/npm
      docker run \
        --rm --privileged --security-opt="seccomp=unconfined" \
        --cap-add=ALL \
        -v /var/lib/containers/:/var/lib/containers/:rw,Z \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $(pwd)/derex/builder/openedx-alpine:/openedx-alpine \
        -v $(pwd)/cache/pip-alpine:/var/cache/pip-alpine \
        -v $(pwd)/cache/apk:/var/cache/apk \
        -v $(pwd)/cache/npm:/var/cache/npm \
        buildah \
        /openedx-alpine/openedx-build/build.sh
    displayName: 'Build open edx image with buildah'

  - task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
    inputs:
      keyfile: 'derex/builder/openedx-alpine/.cache_id'
      targetfolder: 'cache/'
      vstsFeed: '8b1737d6-762a-438d-acf4-e55593dc7819'
    condition: ne(variables['CacheRestored'], 'true')

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: 'Use Python 3.7'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'

