pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: docker pull derex/buildah
    displayName: 'Pull Buildah image'

  - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
    inputs:
      keyfile: 'derex/builder/openedx-alpine/.cache_id'
      targetfolder: 'cache/'
      vstsFeed: '8b1737d6-762a-438d-acf4-e55593dc7819'

  - script: |
      set -x
      docker run \
        --rm --privileged --security-opt="seccomp=unconfined" \
        --cap-add=ALL \
        -v /var/lib/containers/:/var/lib/containers/:rw,Z \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $(pwd):$(pwd) \
        derex/buildah \
        bash -c "
          cd $(pwd)
          python3 setup.py install
          pip3 install pytest pytest-azurepipelines
          pytest tests
        "
    displayName: 'Run tests inside buildah image'

  - task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
    inputs:
      keyfile: 'derex/builder/openedx-alpine/.cache_id'
      targetfolder: 'cache/'
      vstsFeed: '8b1737d6-762a-438d-acf4-e55593dc7819'
    condition: ne(variables['CacheRestored'], 'true')

