pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: docker build buildah -t buildah
    displayName: 'Build Buildah image'

  - script: |
    set -x
    mkdir -p /var/cache/pip-alpine
    mkdir -p /var/cache/apk
    mkdir -p /var/cache/npm
      docker run \
        --rm --privileged --security-opt="seccomp=unconfined" \
        --cap-add=ALL \
        -v /var/lib/containers/:/var/lib/containers/:rw,Z \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $(pwd)/openedx-alpine:/openedx-alpine \
        -v /var/cache/pip-alpine:/var/cache/pip-alpine \
        -v /var/cache/apk:/var/cache/apk \
        -v /var/cache/npm:/var/cache/npm \
        buildah \
        /openedx-alpine/openedx-build/build.sh
    displayName: 'Build open edx image with buildah'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
    displayName: 'Use Python 3.7'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'
